server:
  port: 8123

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: method

spring:
  application:
    name: JobListing
  data:
    mongodb:
      uri: mongodb+srv://mdpritish:pritish1996@pritishpersonalcluster.crmiijz.mongodb.net/?retryWrites=true&w=majority&appName=PritishPersonalCluster
      database: pritish-personal


